---
  - name: week1-1
    cloudformation:
      stack_name: "Week-1-1"
      state: present
      region: "ap-northeast-1"
      disable_rollback: true
      template: "cfn-templates/week1-1.yml"
      stack_policy: "policies/cloudformation/stack-policy.json"
      template_parameters:
        BucketName: "{{bucket_name}}"
