---
  - name: week1-2
    cloudformation:
      stack_name: "Week-1-2"
      state: present
      region: "ap-northeast-1"
      disable_rollback: true
      template: "cfn-templates/week1-2.yml"
      stack_policy: "policies/cloudformation/stack-policy.json"
      template_parameters:
        BucketName: "{{bucket_name}}"
        DomainName: "{{domain_name}}"
        CloudfrontCertARN: "{{cloudfront_cert_arn}}"
        HostedZoneId: "{{hosted_zone_id}}"
        CloudfrontDomainName: "{{cloudfront_domain_name}}"
        ClondfrontCName: "{{cloudfront_cname}}"
