Description: 'Static Web Site'
Parameters:
  BucketName:
    Type: String
    Description: 'Bucket Name'

Resources:
  S3BucketswithWebhosted:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref 'BucketName'
      WebsiteConfiguration:
        IndexDocument: index.html

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref 'BucketName'
      PolicyDocument:
        Statement:
          - Action: ['s3:Get*']
            Effect: Allow
            Principal: "*"
            Resource:
            - !Join ['', ['arn:aws:s3:::', !Ref 'BucketName', /*]]
          - Action: ['s3:List*']
            Effect: Allow
            Principal: "*"
            Resource:
            - !Join ['', ['arn:aws:s3:::', !Ref 'BucketName']]

  myDNS:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Type: A
      HostedZoneId: Z3A46USYXW1L2F
      Name: xian.cutecherry.info
      AliasTarget:
        DNSName: s3-website-ap-northeast-1.amazonaws.com
        EvaluateTargetHealth: True
        HostedZoneId: Z2M4EHUR26P7ZW      