Description: 'Static Web Site'
Parameters:
  BucketName:
    Type: String
    Description: 'Bucket Name'
  DomainName:
    Type: String
    Description: "Domain Name"
  HostedZoneId:
    Type: String
    Description: "Hosted Zone ID"
  AliasS3HostedZoneId:
    Type: String
    Description: "Alias to S3 Hosted Zone ID"
  S3WebEndpoint:
    Type: String
    Description: "Alias to S3 Website Endpoint"

Resources:
  S3BucketswithWebhosted:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref 'BucketName'
      WebsiteConfiguration:
        IndexDocument: index.html

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref 'BucketName'
      PolicyDocument:
        Statement:
          - Action: ['s3:Get*']
            Effect: Allow
            Principal: "*"
            Resource:
            - !Join ['', ['arn:aws:s3:::', !Ref 'BucketName', /*]]
          - Action: ['s3:List*']
            Effect: Allow
            Principal: "*"
            Resource:
            - !Join ['', ['arn:aws:s3:::', !Ref 'BucketName']]

  myDNS:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Type: A
      HostedZoneId: !Ref 'HostedZoneId'
      Name: !Ref 'BucketName'
      AliasTarget:
        DNSName: !Ref 'S3WebEndpoint'
        EvaluateTargetHealth: True
        HostedZoneId: !Ref 'AliasS3HostedZoneId' 