Description: 'Static Web Site'

Parameters:
  BucketName:
    Type: String
    Description: "Bucket Name"
  DomainName:
    Type: String
    Description: "Domain Name"
  CloudfrontCertARN:
    Type: String
  CloudfrontDomainName:
    Type: String
    Description: "Cloundfront DomainName"
  ClondfrontCName:
    Type: String
    Description: "Cloundfront CNames" 
  HostedZoneId:
    Type: String
    Description: "Hosted Zone Id"


Resources:
  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CloudFrontOriginAccessIdentity for Week1

  StaticWebBuckets:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
    
  StaticWebBucketPolicy: 
    Type: "AWS::S3::BucketPolicy"
    Properties: 
      Bucket: 
        Ref: StaticWebBuckets
      PolicyDocument: 
        Statement: 
          - Action: 
              - "s3:GetObject"
            Effect: "Allow"
            Resource: !Sub "arn:aws:s3:::${StaticWebBuckets}/*"
            Principal: 
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"
          
  CloudFront:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases: 
          - !Ref ClondfrontCName
        Enabled: true
        Comment: "created by cloudformation"
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudfrontCertARN
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
        Origins:
          - Id: S3-Origin
            DomainName: !GetAtt StaticWebBuckets.DomainName  #StaticWebBuckets.DomainName = xian.cutecherry.info.s3.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3-Origin
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: 600
          ForwardedValues:
            QueryString: True
            Cookies:
              Forward: all
          Compress: True

  StaticSiteDomainName:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Type: A
      HostedZoneId: !Ref 'HostedZoneId'
      Name: !Ref 'ClondfrontCName'
      AliasTarget:
        DNSName: !GetAtt CloudFront.DomainName  #CloudFront.DomainName = d2pbydp82cq5s1.cloudfront.net.
        HostedZoneId: Z2FDTNDATAQYW2 #Cloudfront Default HostedZoneId

            